services:
  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: yifangyujason/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    ports:
      - 65535:65535
    restart: unless-stopped
