services:
  adminer:
    container_name: adminer
    image: linweiyuan/adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    external: true
