name: chatgpt-proxy-server CI

on:
  push:
    branches: [ "yifangyujason" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: yifangyujason
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./yifangyujason/chatgpt-proxy-server/Dockerfile 
          context: ./yifangyujason/chatgpt-proxy-server
          push: true
          tags: yifangyujason/chatgpt-proxy-server:latest
